services:
    zookeeper1:
        image: bitnami/zookeeper:3.9.0
        container_name: toy-zookeeper1
        hostname: zookeeper1.toy
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        volumes:
            - ./data/zookeeper1/:/bitnami/zookeeper/data/

    kafka1:
        image: bitnami/kafka:3.5
        container_name: toy-kafka1
        depends_on:
            - zookeeper1
        hostname: kafka1.toy
        ports:
            - 9092:9093
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1.toy:2181
            - KAFKA_CFG_NUM_PARTITIONS=1
            - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            # Allow connection outside of Docker Network:
            # promote mapping from localhost:9092 (Docker host) to 0.0.0.0:9093 (on Kafka node).
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=INTERNAL://kafka1.toy:9092,EXTERNAL://0.0.0.0:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1.toy:9092,EXTERNAL://localhost:9092
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
        volumes:
            - ./data/kafka1/:/bitnami/kafka/data/

    kafka-ui:
        image: provectuslabs/kafka-ui:v0.7.2
        container_name: toy-kafka-ui
        hostname: kafka-ui.toy
        ports:
            - 8080:8080
        environment:
            - DYNAMIC_CONFIG_ENABLED=true
        volumes:
            - ./kafka-ui.yaml:/etc/kafkaui/dynamic_config.yaml
